### ISSUE TITLE
.net 5 compatibility

### ISSUE THREAD

**Issue by maxence51** [jmojiwat/FluentAssertions.LanguageExt#1]
Hello @jmojiwat,

Thank you for this great project idea.

Any chance that you can make it compatible with .net 5?

**Comment by jmojiwat** [comment]
Hi @maxence51 ,

Thank you for your kind words.

I'm still new at targeting multiple frameworks on NuGet. I'll have a read up this weekend and see what's needed.

Cheers!

**Comment by maxence51** [comment]
Thank you very much.  No need to rush, don't worry....

**Comment by jmojiwat** [comment]
Hi @maxence51 ,

Adding support just for .NET 5 in addition to .NET 6 wasn't as hard as I thought. On hindsight, I should have read the docs and built against .NET Standard 2.0 from the start.

But .NET 6 is so shiny and new and it felt so good to leave behind .NET Framework 4.8, the framework I used before jumping to .NET 6.

It's on NuGet already. Cheer!
