### ISSUE TITLE
Allow fluent assertion chaining with AndWhichConstraint

### ISSUE THREAD

**Issue by sparerd** [jmojiwat/FluentAssertions.LanguageExt#2]
Hi @jmojiwat, thanks for this library!

I would like to make an enhancement proposal.

FluentAssertions provides an `AndWhichConstraint` type that allows for chaining additional assertions on a sub-type of a parent assertion, similar to the `Be___(action)` overloads in your API.
A potential example usage:
```csharp
Prelude.Some(8)
    .Should().BeSome()
    .Which.Should().Be(8);
```

Benefits to `AndWhichConstraint`:
- Improved discoverability - for those that are used to the `.Which` and `.And` in FluentAssertions, this will feel very familiar.
- Does not interfere with the `Be___(action)` overloads - both options can exist

## Proposal
For any assertion method which asserts a wrapped-value state (BeSome(), BeLeft(), etc), return an `AndWhichConstraint` from the assertion rather than an `AndConstraint`. It probably wouldn't make sense to do this for the `Be___(action)` overloads, since they already support sub-assertions. Or the `Be(expected)` method, since that also doesn't really allow additional assertions. This would just target the `Be___(string, params object[])` overloads.

Since `AndWhichConstraint` derives from `AndConstraint`, this would be a non-breaking change.

Would you be open to this sort of change? If so, I would be happy to open a PR.

## Example change

Original:
```csharp
public AndConstraint<LanguageExtOptionAssertions<T>> BeSome(string because = "", params object[] becauseArgs)
{
    // body ignored, no change needed in assertion logic

    return new AndConstraint<LanguageExtOptionAssertions<T>>(this);
}
```

Modified:
```csharp
public AndWhichConstraint<LanguageExtOptionAssertions<T>, T> BeSome(string because = "", params object[] becauseArgs)
{
    // body ignored, no change needed in assertion logic

    return new AndWhichConstraint<LanguageExtOptionAssertions<T>, T>(this, Subject);
}
```

**Comment by jmojiwat** [comment]
Hi @sparerd ,

Thank you for your kind words.

I totally missed the discussion on AndWhichConstraint discussion in FluentAssertions 6.

Yes, I'm open to this sort of change and appreciate your contribution. Looking forward to your PR.

Cheers!

**Comment by sparerd** [comment]
Great! I'll make the changes and open a PR shortly
