### ISSUE TITLE
"Validation.BeFail().Which" does not allow access to failure list

### ISSUE THREAD

**Issue by sparerd** [jmojiwat/FluentAssertions.LanguageExt#4]
# Problem 
When using the `BeFail()` assertion on a `Validation<TFail, TSucc>`, the `.Which` extension returns only a single failure instance even though the `Validation` type has a `Seq<TFail>`. This prevents proper assertions on the failures returned from a `Validation` using the `.Which` extension.

This bug was introduced when I implemented #3.

# Example
```csharp
using static LanguageExt.Prelude;

// Current valid usage. You can specify a single failure and assert on it just fine.
Validation<int, Unit> v1 = Fail<int, Unit>(1);
v1.Should().BeFail()
    .Which.Should().Be(1); // The "Which" here wraps assertions for type "int"

// Validations can have multiple failures associated with them
Validation<int, Unit> v2 = Fail<int, Unit>(Seq(1, 2, 3));
v2.Should().BeFail()
    .Which.Should().BeEquivalentTo(new[] {1, 2, 3}); // Not valid: "Which" still thinks it is of type "int" when it should be "IEnumerable<int>"
```

# Proposal
There are 2 solutions that I can think of to solve this right now.

## Solution 1 (breaking change)
The simplest solution would be to correct my initial mistake and change the return signature of the `LanguageExtValidationAssertions<TFail, TSuccess>.BeFail()` method from `AndWhichConstraint<LanguageExtValidationAssertions<TFail, TSuccess>, TFail>` to `AndWhichConstraint<LanguageExtValidationAssertions<TFail, TSuccess>, Seq<TFail>>`.

This would offer the most reasonable API surface to users since this mimics the most complex signature available on the `Validation<TFail, TSucc>` type. Here is an example signature: `Validation<TFail, TSucc>.IfFail(Action<Seq<TFail>>)`. The downside of this is that it is a breaking change for anyone who has started using the existing `.Which` extension on `Validation` types.

## Solution 2 (non-breaking change)
The other solution is to introduce another assertion method to handle the case where a validation can have multiple failures.
In this case we would add the method `public AndWhichConstraint<LanguageExtValidationAssertions<TFail, TSuccess>, Seq<TFail>> BeFailEnumerable(string because = "", params object[] becauseArgs)` to the `LanguageExtValidationAssertions<TFail, TSuccess>` class.

Now, if someone wants to assert on a list of failures, they would do something like:
```csharp
using static LanguageExt.Prelude;

// Validations can have multiple failures associated with them
Validation<int, Unit> v2 = Fail<int, Unit>(Seq(1, 2, 3));
v2.Should().BeFailEnumerable()
    .Which.Should().BeEquivalentTo(new[] {1, 2, 3}); // This is now valid. "Which" knows it is an "IEnumerable<int>"
```

**Comment by jmojiwat** [comment]
Hi @sparerd,

Thanks for spotting the bug.

I was comparing with https://fluentassertions.com/collections/ and https://github.com/fluentassertions/fluentassertions.json and it feels to me the more idiomatic way for asserting in fluentassertions would be using Solution 1.

```csharp
validation.Should().BeFail().Which.Should().BeEquivalentTo(new[] {1, 2, 3});
collection.Should().NotBeEmpty().Which.Should().BeEquivalentTo(new[] {1, 2, 3});
```

I feel being idiomatic is more important than breaking change.

Thoughts? Would love to have PR if you have time.

Thanks again!

**Comment by sparerd** [comment]
Yea that sounds good to me. The likelihood of many people depending on the "Validation.Which" extension is probably fairly low. Breaking changes certainly aren't good, but it feels a little nicer to have a single assertion which handles the Validation failure inner type correctly. I'll submit a PR with solution 1 shortly.
