### ISSUE TITLE
FinAssertions's "BeFail" call throws MissingMethodException when LanguageExt >=4.4.0 is used.

### ISSUE THREAD

**Issue by xerocostdistraction** [jmojiwat/FluentAssertions.LanguageExt#7]
When a test project references (directly or indirectly) `LanguageExt.Core` package 4.4.0 and newer, calling `BeFail` on FinAssertions throws the `MissingMethodException`. Calling `BeSuccess`/`BeBottom` doesn't cause any problems.

I suspect it's related to [significant changes](https://github.com/louthy/language-ext/releases/tag/v4.3.0-beta) in `Error` type released in 4.4.0.

The minimal reproducible example is [here](https://github.com/binarybang/fluent-assertions-language-ext-error-demo).

The easiest way to solve this would be to bump the `LanguageExt.Core` dependency to 4.4.0.

**Comment by jmojiwat** [comment]
Hi @binarybang,

Thank you very much for investigating this and suggesting a solution.

I've updated the LanguageExt.Core dependency to 4.4.2 and FluentAssertion dependency to 6.10.0; and added your sample test to the codebase to be sure.

I've also just published an updated nuget package.

Cheers!
